openapi: 3.0.0
info:
  title: DailyReport
  version: '1.0'
  contact:
    email: watertrans@gmail.com
    name: Masahisa Kobayashi
    url: 'https://github.com/watertrans'
  license:
    name: MIT
    url: 'https://github.com/watertrans/DailyReport/blob/main/LICENSE'
  description: The daily report Web API specfications.
servers:
  - url: 'https://localhost:44350/api/v1'
paths:
  /token:
    post:
      summary: アクセストークン発行
      operationId: post-token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
              examples:
                Bearer:
                  value:
                    access_token: HP89YjM-tUqS8In7Av2L2gqQlIWtLxb06fNrp3WU58Kw
                    expires_in: 3600
                    token_type: Bearer
                    scope: full_control read write
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: アクセストークンを発行します。
      security: []
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  enum:
                    - client_credentials
                  example: client_credentials
                  description: 権限種別
                scope:
                  type: string
                  description: スコープ
                  enum:
                    - fullcontrol
                    - read
                    - write
                client_id:
                  type: string
                  description: クライアントID
                  example: owner
                client_secret:
                  type: string
                  description: クライアントシークレット
                  example: owner-secret
              required:
                - grant_type
            examples:
              client_credentials:
                value:
                  grant_type: client_credentials
                  client_id: owner
                  client_secret: owner-secret
        description: ''
      tags:
        - Token
  /persons:
    post:
      summary: 従業員登録
      operationId: post-persons
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
              examples:
                Example:
                  value:
                    personId: f3e5ff26-28ff-4cd6-9b1b-e303a185a13a
                    personCode: '000001'
                    name: John Doe
                    title: Human Resources Manager
                    description: 'Hire date: 2010.04.01'
                    status: NORMAL
                    sortNo: 0
                    tags:
                      - Human Resources
                      - Manager
                      - '2010'
                    createTime: '2021-03-27T14:18:51+09:00'
                    updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: 従業員を登録します。
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                personCode:
                  type: string
                  description: 従業員コード
                  maxLength: 20
                name:
                  type: string
                  maxLength: 100
                  description: 名前
                title:
                  type: string
                  maxLength: 100
                  description: 役職
                description:
                  type: string
                  maxLength: 400
                  description: 説明
                status:
                  type: string
                  enum:
                    - NORMAL
                    - SUSPENDED
                  description: ステータス
                sortNo:
                  type: integer
                  description: 並び順
                  minimum: 0
                  maximum: 2147483647
                tags:
                  type: array
                  minItems: 0
                  maxItems: 10
                  uniqueItems: true
                  description: タグ
                  items:
                    type: string
                    maxLength: 100
              required:
                - personCode
                - name
                - title
                - description
                - status
                - sortNo
                - tags
            examples:
              Example:
                value:
                  personCode: '000001'
                  name: John Doe
                  title: Human Resources Manager
                  description: 'Hire date: 2010.04.01'
                  status: NORMAL
                  sortNo: 0
                  tags:
                    - Human Resources
                    - Manager
                    - '2010'
        description: ''
      tags:
        - Persons
    get:
      summary: 従業員検索
      operationId: get-persons
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                    description: ページ番号
                  pageSize:
                    type: integer
                    description: ページサイズ
                  total:
                    type: integer
                    description: 対象件数
                  items:
                    type: array
                    description: 対象リスト
                    items:
                      $ref: '#/components/schemas/Person'
                required:
                  - page
                  - pageSize
                  - total
                  - items
              examples:
                Example:
                  value:
                    page: 1
                    pageSize: 20
                    total: 1
                    items:
                      - personId: f3e5ff26-28ff-4cd6-9b1b-e303a185a13a
                        personCode: '000001'
                        name: John Doe
                        title: Human Resources Manager
                        description: 'Hire date: 2010.04.01'
                        status: NORMAL
                        sortNo: 0
                        tags:
                          - Human Resources
                          - Manager
                          - '2010'
                        createTime: '2021-03-27T14:18:51+09:00'
                        updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      tags:
        - Persons
      description: |-
        従業員を検索します。
        並び順には次の値を指定できます。
        "SortNo", "PersonCode", "Name", "CreateTime"
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/query'
        - $ref: '#/components/parameters/sort'
  '/persons/{personId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: personId
        in: path
        required: true
        description: 従業員ID
    get:
      summary: 従業員取得
      tags:
        - Persons
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
              examples:
                Example:
                  value:
                    personId: f3e5ff26-28ff-4cd6-9b1b-e303a185a13a
                    personCode: '000001'
                    name: John Doe
                    title: Human Resources Manager
                    description: 'Hire date: 2010.04.01'
                    status: NORMAL
                    sortNo: 0
                    tags:
                      - Human Resources
                      - Manager
                      - '2010'
                    createTime: '2021-03-27T14:18:51+09:00'
                    updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      operationId: get-persons-personId
      description: 従業員を取得します。
    patch:
      summary: 従業員更新
      operationId: patch-persons-personId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
              examples:
                Example:
                  value:
                    personId: f3e5ff26-28ff-4cd6-9b1b-e303a185a13a
                    personCode: '000001'
                    name: John Doe
                    title: Human Resources Manager
                    description: 'Hire date: 2010.04.01'
                    status: NORMAL
                    sortNo: 0
                    tags:
                      - Human Resources
                      - Manager
                      - '2010'
                    createTime: '2021-03-27T14:18:51+09:00'
                    updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: 従業員を更新します。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                personCode:
                  type: string
                  description: 従業員コード
                  maxLength: 20
                name:
                  type: string
                  maxLength: 100
                  description: 名前
                title:
                  type: string
                  maxLength: 100
                  description: 役職
                description:
                  type: string
                  maxLength: 400
                  description: 説明
                status:
                  type: string
                  enum:
                    - NORMAL
                    - SUSPENDED
                  description: ステータス
                sortNo:
                  type: integer
                  description: 並び順
                  minimum: 0
                  maximum: 2147483647
                tags:
                  type: array
                  minItems: 0
                  maxItems: 10
                  uniqueItems: true
                  description: タグ
                  items:
                    type: string
                    maxLength: 100
            examples:
              Example:
                value:
                  personCode: '000001'
                  name: John Doe
                  title: Human Resources Manager
                  description: 'Hire date: 2010.04.01'
                  status: NORMAL
                  sortNo: 0
                  tags:
                    - Human Resources
                    - Manager
                    - '2010'
        description: ''
      tags:
        - Persons
    delete:
      summary: 従業員削除
      operationId: delete-persons-personId
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: 従業員を削除します。
      tags:
        - Persons
  /groups:
    post:
      summary: 部署登録
      operationId: post-groups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
              examples:
                Example:
                  value:
                    groupId: f3e5ff26-28fc-4cd6-9b1b-e303a185a13a
                    groupCode: '000001'
                    groupTree: '00'
                    name: Human Resources
                    description: 'Human resources is the set of people who make up the workforce of an organization, business sector, industry, or economy.'
                    status: NORMAL
                    sortNo: 0
                    tags:
                      - Human Resources
                    createTime: '2021-03-27T14:18:51+09:00'
                    updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: 部署を登録します。
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                groupCode:
                  type: string
                  description: 部署コード
                  maxLength: 20
                groupTree:
                  type: string
                  description: 部署階層
                  maxLength: 8
                name:
                  type: string
                  maxLength: 100
                  description: 名前
                description:
                  type: string
                  maxLength: 400
                  description: 説明
                status:
                  type: string
                  enum:
                    - NORMAL
                    - SUSPENDED
                  description: ステータス
                sortNo:
                  type: integer
                  description: 並び順
                  minimum: 0
                  maximum: 2147483647
                tags:
                  type: array
                  minItems: 0
                  maxItems: 10
                  uniqueItems: true
                  description: タグ
                  items:
                    type: string
                    maxLength: 100
              required:
                - groupCode
                - groupTree
                - name
                - description
                - status
                - sortNo
                - tags
            examples:
              Example:
                value:
                  groupCode: '000001'
                  groupTree: '00'
                  name: Human Resources
                  description: 'Human resources is the set of people who make up the workforce of an organization, business sector, industry, or economy.'
                  status: NORMAL
                  sortNo: 0
                  tags:
                    - Human Resources
        description: ''
      tags:
        - Groups
    get:
      summary: 部署検索
      operationId: get-groups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                    description: ページ番号
                  pageSize:
                    type: integer
                    description: ページサイズ
                  total:
                    type: integer
                    description: 対象件数
                  items:
                    type: array
                    description: 対象リスト
                    items:
                      $ref: '#/components/schemas/Group'
                required:
                  - page
                  - pageSize
                  - total
                  - items
              examples:
                Example:
                  value:
                    page: 1
                    pageSize: 20
                    total: 1
                    items:
                      - groupId: f3e5ff26-28fc-4cd6-9b1b-e303a185a13a
                        groupCode: '000001'
                        groupTree: '00'
                        name: Human Resources
                        description: 'Human resources is the set of people who make up the workforce of an organization, business sector, industry, or economy.'
                        status: NORMAL
                        sortNo: 0
                        tags:
                          - Human Resources
                        createTime: '2021-03-27T14:18:51+09:00'
                        updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      tags:
        - Groups
      description: |-
        部署を検索します。
        並び順には次の値を指定できます。
        "SortNo", "GroupCode", "GroupTree", "Name", "CreateTime"
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/query'
        - $ref: '#/components/parameters/sort'
  '/groups/{groupId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: groupId
        in: path
        required: true
        description: 部署ID
    get:
      summary: 部署取得
      tags:
        - Groups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
              examples:
                Example:
                  value:
                    groupId: f3e5ff26-28fc-4cd6-9b1b-e303a185a13a
                    groupCode: '000001'
                    groupTree: '00'
                    name: Human Resources
                    description: 'Human resources is the set of people who make up the workforce of an organization, business sector, industry, or economy.'
                    status: NORMAL
                    sortNo: 0
                    tags:
                      - Human Resources
                    createTime: '2021-03-27T14:18:51+09:00'
                    updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      operationId: get-groups-groupId
      description: 部署を取得します。
    patch:
      summary: 部署更新
      operationId: patch-groups-groupId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
              examples:
                Example:
                  value:
                    groupId: f3e5ff26-28fc-4cd6-9b1b-e303a185a13a
                    groupCode: '000001'
                    groupTree: '00'
                    name: Human Resources
                    description: 'Human resources is the set of people who make up the workforce of an organization, business sector, industry, or economy.'
                    status: NORMAL
                    sortNo: 0
                    tags:
                      - Human Resources
                    createTime: '2021-03-27T14:18:51+09:00'
                    updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: 部署を更新します。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                groupCode:
                  type: string
                  description: 部署コード
                  maxLength: 20
                groupTree:
                  type: string
                  description: 部署階層
                  maxLength: 8
                name:
                  type: string
                  maxLength: 100
                  description: 名前
                description:
                  type: string
                  maxLength: 400
                  description: 説明
                status:
                  type: string
                  enum:
                    - NORMAL
                    - SUSPENDED
                  description: ステータス
                sortNo:
                  type: integer
                  description: 並び順
                  minimum: 0
                  maximum: 2147483647
                tags:
                  type: array
                  minItems: 0
                  maxItems: 10
                  uniqueItems: true
                  description: タグ
                  items:
                    type: string
                    maxLength: 100
            examples:
              Example:
                value:
                  groupCode: '000001'
                  groupTree: '00'
                  name: Human Resources
                  description: 'Human resources is the set of people who make up the workforce of an organization, business sector, industry, or economy.'
                  status: NORMAL
                  sortNo: 0
                  tags:
                    - Human Resources
        description: ''
      tags:
        - Groups
    delete:
      summary: 部署削除
      operationId: delete-groups-groupId
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: 部署を削除します。
      tags:
        - Groups
  '/groups/{groupId}/persons/{personId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: groupId
        in: path
        required: true
        description: 部署ID
      - schema:
          type: string
          format: uuid
        name: personId
        in: path
        required: true
        description: 従業員ID
    put:
      summary: 部署従業員配属
      operationId: put-groups-groupId-persons-personId
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: 部署に従業員を配属します。
      tags:
        - Groups
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                positionType:
                  type: string
                  description: 配属タイプ
                  enum:
                    - GENERAL_MANAGER
                    - MANAGER
                    - STAFF
                  example: STAFF
              required:
                - positionType
            examples: {}
    delete:
      summary: 部署従業員解除
      operationId: delete-groups-groupId-persons-personId
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: 部署の従業員を解除します。
      tags:
        - Groups
  '/groups/{groupId}/persons':
    parameters:
      - schema:
          type: string
          format: uuid
        name: groupId
        in: path
        required: true
        description: 部署ID
    get:
      summary: 部署従業員検索
      tags:
        - Groups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                    description: ページ番号
                  pageSize:
                    type: integer
                    description: ページサイズ
                  total:
                    type: integer
                    description: 対象件数
                  items:
                    type: array
                    description: 対象リスト
                    items:
                      $ref: '#/components/schemas/GroupPerson'
                required:
                  - page
                  - pageSize
                  - total
                  - items
              examples:
                Example:
                  value:
                    page: 1
                    pageSize: 20
                    total: 1
                    items:
                      - personId: f3e5ff26-28ff-4cd6-9b1b-e303a185a13a
                        personCode: '000001'
                        name: John Doe
                        title: Human Resources Manager
                        description: 'Hire date: 2010.04.01'
                        status: NORMAL
                        sortNo: 0
                        tags:
                          - Human Resources
                          - Manager
                          - '2010'
                        positionType: STAFF
                        createTime: '2021-03-27T14:18:51+09:00'
                        updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      operationId: get-groups-groudId-persons
      description: |-
        部署の従業員を検索します。
        並び順には次の値を指定できます。
        "SortNo", "PersonCode", "Name", "CreateTime"
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/query'
        - $ref: '#/components/parameters/sort'
  /projects:
    post:
      summary: プロジェクト登録
      operationId: post-projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
              examples:
                Example:
                  value:
                    projectId: f3e5ff26-28fe-4cd6-9b1b-e303a185a13a
                    projectCode: '000001'
                    name: Software Development
                    description: 'Software development is the process of conceiving, specifying, designing, programming, documenting, testing, and bug fixing involved in creating and maintaining applications, frameworks, or other software components.'
                    status: NORMAL
                    sortNo: 0
                    tags:
                      - Software Development
                    createTime: '2021-03-27T14:18:51+09:00'
                    updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: プロジェクトを登録します。
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                projectCode:
                  type: string
                  description: プロジェクトコード
                  maxLength: 20
                name:
                  type: string
                  maxLength: 100
                  description: 名前
                description:
                  type: string
                  maxLength: 400
                  description: 説明
                status:
                  type: string
                  enum:
                    - NORMAL
                    - SUSPENDED
                  description: ステータス
                sortNo:
                  type: integer
                  description: 並び順
                  minimum: 0
                  maximum: 2147483647
                tags:
                  type: array
                  minItems: 0
                  maxItems: 10
                  uniqueItems: true
                  description: タグ
                  items:
                    type: string
                    maxLength: 100
              required:
                - projectCode
                - name
                - description
                - status
                - sortNo
                - tags
            examples:
              Example:
                value:
                  projectCode: '000001'
                  name: Software Development
                  description: 'Software development is the process of conceiving, specifying, designing, programming, documenting, testing, and bug fixing involved in creating and maintaining applications, frameworks, or other software components.'
                  status: NORMAL
                  sortNo: 0
                  tags:
                    - Software Development
        description: ''
      tags:
        - Projects
    get:
      summary: プロジェクト検索
      operationId: get-projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                    description: ページ番号
                  pageSize:
                    type: integer
                    description: ページサイズ
                  total:
                    type: integer
                    description: 対象件数
                  items:
                    type: array
                    description: 対象リスト
                    items:
                      $ref: '#/components/schemas/Project'
                required:
                  - page
                  - pageSize
                  - total
                  - items
              examples:
                Example:
                  value:
                    page: 1
                    pageSize: 20
                    total: 1
                    items:
                      - projectId: f3e5ff26-28fe-4cd6-9b1b-e303a185a13a
                        projectCode: '000001'
                        name: Software Development
                        description: 'Software development is the process of conceiving, specifying, designing, programming, documenting, testing, and bug fixing involved in creating and maintaining applications, frameworks, or other software components.'
                        status: NORMAL
                        sortNo: 0
                        tags:
                          - Software Development
                        createTime: '2021-03-27T14:18:51+09:00'
                        updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      tags:
        - Projects
      description: |-
        プロジェクトを検索します。
        並び順には次の値を指定できます。
        "SortNo", "ProjectCode", "Name", "CreateTime"
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/query'
        - $ref: '#/components/parameters/sort'
  '/projects/{projectId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: projectId
        in: path
        required: true
        description: プロジェクトID
    get:
      summary: プロジェクト取得
      tags:
        - Projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
              examples:
                Example:
                  value:
                    projectId: f3e5ff26-28fe-4cd6-9b1b-e303a185a13a
                    projectCode: '000001'
                    name: Software Development
                    description: 'Software development is the process of conceiving, specifying, designing, programming, documenting, testing, and bug fixing involved in creating and maintaining applications, frameworks, or other software components.'
                    status: NORMAL
                    sortNo: 0
                    tags:
                      - Software Development
                    createTime: '2021-03-27T14:18:51+09:00'
                    updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      operationId: get-projects-projectId
      description: プロジェクトを取得します。
    patch:
      summary: プロジェクト更新
      operationId: patch-projects-projectId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
              examples:
                Example:
                  value:
                    projectId: f3e5ff26-28fe-4cd6-9b1b-e303a185a13a
                    projectCode: '000001'
                    name: Software Development
                    description: 'Software development is the process of conceiving, specifying, designing, programming, documenting, testing, and bug fixing involved in creating and maintaining applications, frameworks, or other software components.'
                    status: NORMAL
                    sortNo: 0
                    tags:
                      - Software Development
                    createTime: '2021-03-27T14:18:51+09:00'
                    updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: プロジェクトを更新します。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                projectCode:
                  type: string
                  description: プロジェクトコード
                  maxLength: 20
                name:
                  type: string
                  maxLength: 100
                  description: 名前
                description:
                  type: string
                  maxLength: 400
                  description: 説明
                status:
                  type: string
                  enum:
                    - NORMAL
                    - SUSPENDED
                  description: ステータス
                sortNo:
                  type: integer
                  description: 並び順
                  minimum: 0
                  maximum: 2147483647
                tags:
                  type: array
                  minItems: 0
                  maxItems: 10
                  uniqueItems: true
                  description: タグ
                  items:
                    type: string
                    maxLength: 100
            examples:
              Example:
                value:
                  projectCode: '000001'
                  name: Software Development
                  description: 'Software development is the process of conceiving, specifying, designing, programming, documenting, testing, and bug fixing involved in creating and maintaining applications, frameworks, or other software components.'
                  status: NORMAL
                  sortNo: 0
                  tags:
                    - Software Development
        description: ''
      tags:
        - Projects
    delete:
      summary: プロジェクト削除
      operationId: delete-projects-projectId
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: プロジェクトを削除します。
      tags:
        - Projects
  '/projects/{projectId}/persons/{personId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: projectId
        in: path
        required: true
        description: プロジェクトID
      - schema:
          type: string
          format: uuid
        name: personId
        in: path
        required: true
        description: 従業員ID
    put:
      summary: プロジェクト従業員配属
      operationId: put-projects-projectId-persons-personId
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: プロジェクトに従業員を配属します。
      tags:
        - Projects
    delete:
      summary: プロジェクト従業員解除
      operationId: delete-projects-projectId-persons-personId
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      description: プロジェクトの従業員を解除します。
      tags:
        - Projects
  '/projects/{projectId}/persons':
    parameters:
      - schema:
          type: string
          format: uuid
        name: projectId
        in: path
        required: true
        description: プロジェクトID
    get:
      summary: プロジェクト従業員検索
      tags:
        - Projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                    description: ページ番号
                  pageSize:
                    type: integer
                    description: ページサイズ
                  total:
                    type: integer
                    description: 対象件数
                  items:
                    type: array
                    description: 対象リスト
                    items:
                      $ref: '#/components/schemas/Person'
                required:
                  - page
                  - pageSize
                  - total
                  - items
              examples:
                Example:
                  value:
                    page: 1
                    pageSize: 20
                    total: 1
                    items:
                      - personId: f3e5ff26-28ff-4cd6-9b1b-e303a185a13a
                        personCode: '000001'
                        name: John Doe
                        title: Software Development Manager
                        description: 'Hire date: 2010.04.01'
                        status: NORMAL
                        sortNo: 0
                        tags:
                          - Software Development
                          - Manager
                          - '2010'
                        createTime: '2021-03-27T14:18:51+09:00'
                        updateTime: '2021-03-27T14:18:51+09:00'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      operationId: get-projects-groudId-persons
      description: |-
        プロジェクトの従業員を検索します。
        並び順には次の値を指定できます。
        "SortNo", "PersonCode", "Name", "CreateTime"
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/query'
        - $ref: '#/components/parameters/sort'
components:
  schemas:
    Error:
      title: Error
      type: object
      x-examples:
        NotFound:
          message: 指定したリソースは存在しません。
          code: NotFound
        ValidationError:
          code: ValidationError
          message: 入力エラーが発生しました。エラーメッセージを確認してください。
          details:
            - message: '''ステータス''の値が正しくありません。'
              target: status
              code: ValidationErrorDetail
      description: エラー
      properties:
        code:
          type: string
          description: エラーコード
        message:
          type: string
          description: エラーメッセージ
        details:
          type: array
          description: エラー詳細
          items:
            $ref: '#/components/schemas/Error'
        target:
          type: string
          description: エラーターゲット
        innerError:
          $ref: '#/components/schemas/Error'
      required:
        - code
        - message
    Group:
      title: Group
      type: object
      description: 部署
      x-examples:
        Human Resources:
          groupId: f3e5ff26-28fc-4cd6-9b1b-e303a185a13a
          groupCode: '000001'
          groupTree: '00'
          name: Human Resources
          description: 'Human resources is the set of people who make up the workforce of an organization, business sector, industry, or economy.'
          status: NORMAL
          sortNo: 0
          tags:
            - Human Resources
          createTime: '2021-03-27T14:18:51+09:00'
          updateTime: '2021-03-27T14:18:51+09:00'
      properties:
        groupId:
          type: string
          description: 部署ID
          format: uuid
        groupCode:
          type: string
          description: 部署コード
          maxLength: 20
        groupTree:
          type: string
          description: 部署階層
          maxLength: 8
        name:
          type: string
          maxLength: 100
          description: 名前
        description:
          type: string
          description: 説明
          maxLength: 400
        status:
          type: string
          enum:
            - NORMAL
            - SUSPENDED
          description: ステータス
        sortNo:
          type: integer
          description: 並び順
          minimum: 0
          exclusiveMaximum: false
          maximum: 2147483647
        tags:
          type: array
          format: date
          description: タグ
          minItems: 0
          maxItems: 10
          uniqueItems: true
          items:
            type: string
        createTime:
          type: string
          description: 作成日時
        updateTime:
          type: string
          description: 更新日時
      required:
        - groupId
        - groupCode
        - groupTree
        - name
        - description
        - status
        - sortNo
        - tags
        - createTime
        - updateTime
    Person:
      title: Person
      type: object
      description: 従業員
      x-examples:
        John Doe:
          personId: f3e5ff26-28ff-4cd6-9b1b-e303a185a13a
          personCode: '000001'
          name: John Doe
          title: Human Resources Manager
          description: 'Hire date: 2010.04.01'
          status: NORMAL
          sortNo: 0
          tags:
            - Human Resources
            - Manager
            - '2010'
          createTime: '2021-03-27T14:18:51+09:00'
          updateTime: '2021-03-27T14:18:51+09:00'
      properties:
        personId:
          type: string
          description: 従業員ID
          format: uuid
        personCode:
          type: string
          description: 従業員コード
          maxLength: 20
        name:
          type: string
          maxLength: 100
          description: 名前
        title:
          type: string
          description: 役職
          maxLength: 100
        description:
          type: string
          description: 説明
          maxLength: 400
        status:
          type: string
          enum:
            - NORMAL
            - SUSPENDED
          description: ステータス
        sortNo:
          type: integer
          description: 並び順
          minimum: 0
          exclusiveMaximum: false
          maximum: 2147483647
        tags:
          type: array
          format: date
          description: タグ
          minItems: 0
          maxItems: 10
          uniqueItems: true
          items:
            type: string
        createTime:
          type: string
          description: 作成日時
        updateTime:
          type: string
          description: 更新日時
      required:
        - personId
        - personCode
        - name
        - title
        - description
        - status
        - sortNo
        - tags
        - createTime
        - updateTime
    GroupPerson:
      title: GroupPerson
      type: object
      description: 部署所属従業員
      x-examples:
        John Doe:
          personId: f3e5ff26-28ff-4cd6-9b1b-e303a185a13a
          personCode: '000001'
          name: John Doe
          title: Human Resources Manager
          description: 'Hire date: 2010.04.01'
          status: NORMAL
          sortNo: 0
          tags:
            - Human Resources
            - Manager
            - '2010'
          positionType: STAFF
          createTime: '2021-03-27T14:18:51+09:00'
          updateTime: '2021-03-27T14:18:51+09:00'
      properties:
        personId:
          type: string
          description: 従業員ID
          format: uuid
        personCode:
          type: string
          description: 従業員コード
          maxLength: 20
        name:
          type: string
          maxLength: 100
          description: 名前
        title:
          type: string
          description: 役職
          maxLength: 100
        description:
          type: string
          description: 説明
          maxLength: 400
        status:
          type: string
          enum:
            - NORMAL
            - SUSPENDED
          description: ステータス
        sortNo:
          type: integer
          description: 並び順
          minimum: 0
          exclusiveMaximum: false
          maximum: 2147483647
        tags:
          type: array
          format: date
          description: タグ
          minItems: 0
          maxItems: 10
          uniqueItems: true
          items:
            type: string
        positionType:
          type: string
          description: 配属タイプ
          example: STAFF
          enum:
            - GENERAL_MANAGER
            - MANAGER
            - STAFF
        createTime:
          type: string
          description: 作成日時
        updateTime:
          type: string
          description: 更新日時
      required:
        - personId
        - personCode
        - name
        - title
        - description
        - status
        - sortNo
        - tags
        - positionType
        - createTime
        - updateTime
    Project:
      title: Project
      type: object
      description: プロジェクト
      x-examples:
        Human Resources:
          projectId: f3e5ff26-28fe-4cd6-9b1b-e303a185a13a
          projectCode: '000001'
          name: Software Development
          description: 'Software development is the process of conceiving, specifying, designing, programming, documenting, testing, and bug fixing involved in creating and maintaining applications, frameworks, or other software components.'
          status: NORMAL
          sortNo: 0
          tags:
            - Software Development
          createTime: '2021-03-27T14:18:51+09:00'
          updateTime: '2021-03-27T14:18:51+09:00'
      properties:
        projectId:
          type: string
          description: プロジェクトID
          format: uuid
        projectCode:
          type: string
          description: プロジェクトコード
          maxLength: 20
        name:
          type: string
          maxLength: 100
          description: 名前
        description:
          type: string
          description: 説明
          maxLength: 400
        status:
          type: string
          enum:
            - NORMAL
            - SUSPENDED
          description: ステータス
        sortNo:
          type: integer
          description: 並び順
          minimum: 0
          exclusiveMaximum: false
          maximum: 2147483647
        tags:
          type: array
          format: date
          description: タグ
          minItems: 0
          maxItems: 10
          uniqueItems: true
          items:
            type: string
        createTime:
          type: string
          description: 作成日時
        updateTime:
          type: string
          description: 更新日時
      required:
        - projectId
        - projectCode
        - name
        - description
        - status
        - sortNo
        - tags
        - createTime
        - updateTime
    Token:
      title: Token
      type: object
      description: アクセストークン
      properties:
        access_token:
          type: string
          description: アクセストークン
          maxLength: 100
        expires_in:
          type: integer
          description: アクセストークンの存続時間（秒単位）
        token_type:
          type: string
          description: トークンタイプ
        scope:
          type: string
          description: スコープ
      required:
        - access_token
        - expires_in
        - token_type
        - scope
      x-examples:
        Bearer:
          access_token: HP89YjM-tUqS8In7Av2L2gqQlIWtLxb06fNrp3WU58Kw
          expires_in: 3600
          token_type: Bearer
          scope: full_control read write
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
  responses:
    400BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example:
              value:
                code: BadRequest
                message: 要求が正しくありません。
    401Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example:
              value:
                code: Unauthorized
                message: 認証情報が正しくありません。
    403Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example:
              value:
                code: Forbidden
                message: 指定した操作を実行するアクセス権がありません。
    404NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example:
              value:
                code: NotFound
                message: 指定したリソースは存在しません。
    500InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example:
              value:
                code: InternalServerError
                message: サーバーで予期しないエラーが発生しました。
  parameters:
    page:
      name: page
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 999
        default: 1
      description: ページ番号
    pageSize:
      name: pageSize
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
      description: ページサイズ
    sort:
      name: sort
      in: query
      required: false
      schema:
        type: string
        example: 'sortNo,-createTime'
        maxLength: 100
      description: 並び順（カンマ区切りで複数指定可、各項目に-プレフィクス付与で降順）
    query:
      name: query
      in: query
      required: false
      schema:
        type: string
        maxLength: 100
      description: 検索キーワード
  examples: {}
security:
  - Bearer: []
tags:
  - name: Debug
  - name: Groups
  - name: Persons
  - name: Projects
  - name: Token
